### ISSUE TITLE
support for setJointMotorControl2 method

### ISSUE THREAD

**Issue by ashvath100** [robotlearn/pyrobolearn#39]
setJointMotorControl is obsolete and replaced by setJointMotorControl2 API , but this is not yet reflected in pyrobolearn

**Comment by lrozo** [comment]
Hi @ashvath100 !
Nice to see you are using our framework! 😄 I am wondering why you think this is not currently reflected in pyrobolearn. If you have a look at our backend for PyBullet ([here](https://github.com/robotlearn/pyrobolearn/blob/master/pyrobolearn/simulators/bullet.py)), we actually use ` setJointMotorControl2`. Are we missing this somewhere else?

**Comment by ashvath100** [comment]
My bad, I was missled when I got an unexpected keyword argumet error  while using keyword maxVelocity as mentioned in [here](https://github.com/robotlearn/pyrobolearn/blob/c70e5b7b9b7b649a25b73dbc58aabe84a4daa6ab/pyrobolearn/robots/robot.py#L1370) while it actualy is max_velocity
