### ISSUE TITLE
failed to load python extension for lz4 support. lz4 compression will not be available

### ISSUE THREAD

**Issue by HongminWu** [robotlearn/pyrobolearn#45]
After installation, when import pyrobolearn, get the following error:

` Failed to load python extension for lz4 support. lz4 compression will not be available.
pybullet build time: Oct 8 2020 00:10:04
Dart could not be found on this system... SKipping prl.simulators.Dart...
ERROR: Expired activation key`

**Comment by lrozo** [comment]
Hi,

May you please be more specific about the OS you are using, how you are creating the virtual environment and any other steps you followed when facing this problem? That would be useful to try to reproduce the problem you are currently experiencing.

Best,

Leonel

**Comment by wq-wust** [comment]
Hi,

I have a similar problem. I want to know how to run examples/robots/xxx.py is the correct command.
`(env) wq@wq:~/pyrobolearn/examples/robots$ python load_robot.py  

Failed to load Python extension for LZ4 support. LZ4 compression will not be available.
Some ROS packages were not found... Skipping prl.simulators.middlewares.ROS...
pybullet build time: Nov 26 2020 23:07:47
Dart could not be found on this system... Skipping prl.simulators.Dart...
MuJoCo could not be found on this system... Skipping prl.simulators.Mujoco...
Raisim could not be found on this system... Skipping prl.simulators.Raisim...
Traceback (most recent call last):
  File "load_robot.py", line 18, in <module>
    import pyrobolearn as prl
  File "/home/wq/pyrobolearn/pyrobolearn/__init__.py", line 31, in <module>
    from . import worlds
  File "/home/wq/pyrobolearn/pyrobolearn/worlds/__init__.py", line 7, in <module>
    from .world import World, BasicWorld
  File "/home/wq/pyrobolearn/pyrobolearn/worlds/world.py", line 15, in <module>
    import cv2
ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type
`

Experimental environment: Ubuntu1604 python3.6

**Comment by lrozo** [comment]
The examples in `pyrobolearn/examples/robots/` are currently running using Ubuntu 16.04 and python 3.6. I am afraid you may have some issues regarding your virtual env. configuration, as `import cv2` seems to be using python2.7 and not python3.6, as the error suggests: 
`import cv2
ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type`
