### ISSUE TITLE
Execution failure due to Non-ASCII characters (Bug)

### ISSUE THREAD

**Issue by markusgft** [robotlearn/pyrobolearn#5]
When trying to run any example, for example:

`pyrobolearn_ws/pyrobolearn/examples/kinematics/forward$ python fk.py 
pybullet build time: Sep 25 2019 10:28:00
current_dir .../.virtualenvs/venv_py2/local/lib/python2.7/site-packages/pybullet_envs/bullet
Traceback (most recent call last):
  File "fk.py", line 11, in <module>
    from pyrobolearn.simulators import Bullet
  File "/packages/pyrobolearn/pyrobolearn/__init__.py", line 23, in <module>
    from . import simulators
  File "/packages/pyrobolearn/pyrobolearn/simulators/__init__.py", line 35, in <module>
    from .raisim import Raisim
  File "/packages/pyrobolearn/pyrobolearn/simulators/raisim.py", line 31
SyntaxError: Non-ASCII character '\xe2' in file /home/gim2rng/packages/pyrobolearn/pyrobolearn/simulators/raisim.py on line 32, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
`
I started tracing back the non-readable characters, however they are numerous. Possibly introduced by editing the documentation sections in an inappropriate text-editor.

**Comment by dbonattoj** [comment]
Dear @markusgft,

Which OS are you using? At the moment I'm unable to reproduce the bug (Windows and Linux). However, I think that writing:

`# -*- coding: utf-8 -*-`

at the beginning of each file should work.

Could you put this string at the beginning of "pyrobolearn/pyrobolearn/simulators/raisim.py" and try again? If it work I'm sure @bdelhaisse will update all the files :)

Best regards,

**Comment by markusgft** [comment]
Dear @dbonattoj , @bdelhaisse 

We are on Ubuntu 18.04 and I run into the issue using both py2.7 and py3.6 in clean virtual environments.
As you suggested, adding `# -*- coding: utf-8 -*-` solves the problem, however, it has to be included in every affected file. It would be great if you could take care of that issue and push a fix soon!

Best!

**Comment by dbonattoj** [comment]
I've made a PR for @bdelhaisse to check :)

https://github.com/robotlearn/pyrobolearn/pull/6

Best regards,

**Comment by bdelhaisse** [comment]
I am currently in the middle of something. I will try to check the PR tonight (or at worst, tomorrow morning/noon).

Best.
