### ISSUE TITLE
Error while running pendulum control environment in pyrobolearn

### ISSUE THREAD

**Issue by deepakraina99** [robotlearn/pyrobolearn#53]
I am getting the following error when I run the pendulum.py file:

```
ImportError: cannot import name 'robot_names_to_classes' from partially initialized module 'pyrobolearn.robots' (most likely due to a circular import) (/home/$USER/$DIRECTORY/pyrobolearn-master/pyrobolearn/robots/__init__.py)
```

**Comment by lrozo** [comment]
We do not get such an error, may you please be more specific about your configuration, python version in your virtual environment, and display all the info regarding the error?

**Comment by lrozo** [comment]
No further replies from the reporter.
