### ISSUE TITLE
Reaching environment is not showing any change in response to action

### ISSUE THREAD

**Issue by deepakraina99** [robotlearn/pyrobolearn#54]
I am testing it using the following code in reaching.py

```
# Test
if __name__ == "__main__":
    from itertools import count
    import pyrobolearn as prl

    # create simulator
    sim = prl.simulators.Bullet()

    # create environment
    env = ReachingManipulationEnv(sim, control_mode = 'torque')
    action = env.action
    action.data = np.array([1,0,0,20,0,0,0])
    print("\nAction: {}".format(action))
    # run simulation
    for _ in count():
        # print(action)
        env.step(action, sleep_dt=1./240)
```

Please guide me on what I am missing here.
Thanks.

**Comment by deepakraina99** [comment]
Basically, all environments in PRL shows no movement when loaded. How the action (joint position change, velocity change, etc.) are being applied in these environments?

**Comment by lrozo** [comment]
Please check `pyrobolearn/examples/enviroments/inverted_pendulum` for a full example on how to define and use environments.
