### ISSUE TITLE
trajectory visualization

### ISSUE THREAD

**Issue by HongminWu** [robotlearn/pyrobolearn#55]
How can we implement the trajectory  visualization of robot end-effector as shown in your paper?

**Comment by lrozo** [comment]
Which visualization do you refer to (i.e., which figure in our paper)?

**Comment by HongminWu** [comment]
Sorry for the unclear expression. 
It's the figure 3 in paper titled "PyRoboLearn: A Python Framework for Robot Learning Practitioners"

**Comment by lrozo** [comment]
We have some basic plotting functionalities in `pyrobolearn/utils/plotting/`. Have a look at them there, you may find some of them useful.
