### ISSUE TITLE
Please create humanoid IK tutorials such as robot standing or robot horizontal walking

### ISSUE THREAD

**Issue by softmurata** [robotlearn/pyrobolearn#56]
Hi, thanks you for your effort to making good implementations of pyRobolearn.
I would like to know the usage of humanoid IK(for example, robot standing or robot horizontal walking). 
I try to load humanoid and apply inverse kinematics code which you publish on github, but I got some errors and did not work well.
Please make some tutorials about humanoid version!!

**Comment by lrozo** [comment]
Hi,
We have some experiments about robot manipulability control that use a very simple balancing control for humanoids (check `pyrobolearn/examples/manipulability`. You may find this controller useful as a starting point for more sophisticated (e.g, SPQ) controllers. 
We will be very happy to get contributions from your side regarding these examples for humanoid robots, please feel welcome to contribute!

**Comment by softmurata** [comment]
Thanks for your replay.
I will try those projects and learn the control of humanoid robots.
If I have some problems, I will post some questions in this github. I expect you to give some good instructions in such cases.
