### ISSUE TITLE
Error in /examples/imitation/trajectory_reproduction_kuka_dmp.py

### ISSUE THREAD

**Issue by deepakraina99** [robotlearn/pyrobolearn#59]
When I run this file, first I record the trajectory using ctrl+r and then by pressing shift+r, it fails to execute and gives the following error:
```
TypeError: Expecting an instance of `Action`, np.array, or a list of the previous ones, but got instead: <class 'numpy.ndarray'>
```

Please help.

**Comment by lrozo** [comment]
Hi, 

This code has been tested in several machines with different configurations without reporting the same error. May you please provide the python version you use, Linux machine, and other dependencies? Without this, it is very hard for us to get where this error comes from.

**Comment by deepakraina99** [comment]
Hi, thanks for your response. 
I am using python 3.8.5 and use Ubuntu 20.04.2 LTS OS. I have also attached the list of packages in my environment.

[packages_in_env.txt](https://github.com/robotlearn/pyrobolearn/files/6366864/packages_in_env.txt)

**Comment by deepakraina99** [comment]
This issue is resolved by changing line 49 of this code to ```env = Env(world, state, actions=action)```
I have proposed the changes also.

Thanks, @lrozo for your support.
